/*
Market Data

Testing InstrumentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/kebroad/schwab-accounts-and-trading-production-go"
)

func Test_client_InstrumentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InstrumentsAPIService GetInstruments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstrumentsAPI.GetInstruments(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstrumentsAPIService GetInstrumentsByCusip", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cusipId string

		resp, httpRes, err := apiClient.InstrumentsAPI.GetInstrumentsByCusip(context.Background(), cusipId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
