/*
Market Data

Trader API - Market data

API version: 1.0.0
Contact: TraderAPI@Schwab.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the Underlying type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Underlying{}

// Underlying struct for Underlying
type Underlying struct {
	Ask *float64 `json:"ask,omitempty"`
	AskSize *int32 `json:"askSize,omitempty"`
	Bid *float64 `json:"bid,omitempty"`
	BidSize *int32 `json:"bidSize,omitempty"`
	Change *float64 `json:"change,omitempty"`
	Close *float64 `json:"close,omitempty"`
	Delayed *bool `json:"delayed,omitempty"`
	Description *string `json:"description,omitempty"`
	ExchangeName *string `json:"exchangeName,omitempty"`
	FiftyTwoWeekHigh *float64 `json:"fiftyTwoWeekHigh,omitempty"`
	FiftyTwoWeekLow *float64 `json:"fiftyTwoWeekLow,omitempty"`
	HighPrice *float64 `json:"highPrice,omitempty"`
	Last *float64 `json:"last,omitempty"`
	LowPrice *float64 `json:"lowPrice,omitempty"`
	Mark *float64 `json:"mark,omitempty"`
	MarkChange *float64 `json:"markChange,omitempty"`
	MarkPercentChange *float64 `json:"markPercentChange,omitempty"`
	OpenPrice *float64 `json:"openPrice,omitempty"`
	PercentChange *float64 `json:"percentChange,omitempty"`
	QuoteTime *int64 `json:"quoteTime,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
	TotalVolume *int64 `json:"totalVolume,omitempty"`
	TradeTime *int64 `json:"tradeTime,omitempty"`
}

// NewUnderlying instantiates a new Underlying object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnderlying() *Underlying {
	this := Underlying{}
	return &this
}

// NewUnderlyingWithDefaults instantiates a new Underlying object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnderlyingWithDefaults() *Underlying {
	this := Underlying{}
	return &this
}

// GetAsk returns the Ask field value if set, zero value otherwise.
func (o *Underlying) GetAsk() float64 {
	if o == nil || IsNil(o.Ask) {
		var ret float64
		return ret
	}
	return *o.Ask
}

// GetAskOk returns a tuple with the Ask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetAskOk() (*float64, bool) {
	if o == nil || IsNil(o.Ask) {
		return nil, false
	}
	return o.Ask, true
}

// HasAsk returns a boolean if a field has been set.
func (o *Underlying) HasAsk() bool {
	if o != nil && !IsNil(o.Ask) {
		return true
	}

	return false
}

// SetAsk gets a reference to the given float64 and assigns it to the Ask field.
func (o *Underlying) SetAsk(v float64) {
	o.Ask = &v
}

// GetAskSize returns the AskSize field value if set, zero value otherwise.
func (o *Underlying) GetAskSize() int32 {
	if o == nil || IsNil(o.AskSize) {
		var ret int32
		return ret
	}
	return *o.AskSize
}

// GetAskSizeOk returns a tuple with the AskSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetAskSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.AskSize) {
		return nil, false
	}
	return o.AskSize, true
}

// HasAskSize returns a boolean if a field has been set.
func (o *Underlying) HasAskSize() bool {
	if o != nil && !IsNil(o.AskSize) {
		return true
	}

	return false
}

// SetAskSize gets a reference to the given int32 and assigns it to the AskSize field.
func (o *Underlying) SetAskSize(v int32) {
	o.AskSize = &v
}

// GetBid returns the Bid field value if set, zero value otherwise.
func (o *Underlying) GetBid() float64 {
	if o == nil || IsNil(o.Bid) {
		var ret float64
		return ret
	}
	return *o.Bid
}

// GetBidOk returns a tuple with the Bid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetBidOk() (*float64, bool) {
	if o == nil || IsNil(o.Bid) {
		return nil, false
	}
	return o.Bid, true
}

// HasBid returns a boolean if a field has been set.
func (o *Underlying) HasBid() bool {
	if o != nil && !IsNil(o.Bid) {
		return true
	}

	return false
}

// SetBid gets a reference to the given float64 and assigns it to the Bid field.
func (o *Underlying) SetBid(v float64) {
	o.Bid = &v
}

// GetBidSize returns the BidSize field value if set, zero value otherwise.
func (o *Underlying) GetBidSize() int32 {
	if o == nil || IsNil(o.BidSize) {
		var ret int32
		return ret
	}
	return *o.BidSize
}

// GetBidSizeOk returns a tuple with the BidSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetBidSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.BidSize) {
		return nil, false
	}
	return o.BidSize, true
}

// HasBidSize returns a boolean if a field has been set.
func (o *Underlying) HasBidSize() bool {
	if o != nil && !IsNil(o.BidSize) {
		return true
	}

	return false
}

// SetBidSize gets a reference to the given int32 and assigns it to the BidSize field.
func (o *Underlying) SetBidSize(v int32) {
	o.BidSize = &v
}

// GetChange returns the Change field value if set, zero value otherwise.
func (o *Underlying) GetChange() float64 {
	if o == nil || IsNil(o.Change) {
		var ret float64
		return ret
	}
	return *o.Change
}

// GetChangeOk returns a tuple with the Change field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetChangeOk() (*float64, bool) {
	if o == nil || IsNil(o.Change) {
		return nil, false
	}
	return o.Change, true
}

// HasChange returns a boolean if a field has been set.
func (o *Underlying) HasChange() bool {
	if o != nil && !IsNil(o.Change) {
		return true
	}

	return false
}

// SetChange gets a reference to the given float64 and assigns it to the Change field.
func (o *Underlying) SetChange(v float64) {
	o.Change = &v
}

// GetClose returns the Close field value if set, zero value otherwise.
func (o *Underlying) GetClose() float64 {
	if o == nil || IsNil(o.Close) {
		var ret float64
		return ret
	}
	return *o.Close
}

// GetCloseOk returns a tuple with the Close field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetCloseOk() (*float64, bool) {
	if o == nil || IsNil(o.Close) {
		return nil, false
	}
	return o.Close, true
}

// HasClose returns a boolean if a field has been set.
func (o *Underlying) HasClose() bool {
	if o != nil && !IsNil(o.Close) {
		return true
	}

	return false
}

// SetClose gets a reference to the given float64 and assigns it to the Close field.
func (o *Underlying) SetClose(v float64) {
	o.Close = &v
}

// GetDelayed returns the Delayed field value if set, zero value otherwise.
func (o *Underlying) GetDelayed() bool {
	if o == nil || IsNil(o.Delayed) {
		var ret bool
		return ret
	}
	return *o.Delayed
}

// GetDelayedOk returns a tuple with the Delayed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetDelayedOk() (*bool, bool) {
	if o == nil || IsNil(o.Delayed) {
		return nil, false
	}
	return o.Delayed, true
}

// HasDelayed returns a boolean if a field has been set.
func (o *Underlying) HasDelayed() bool {
	if o != nil && !IsNil(o.Delayed) {
		return true
	}

	return false
}

// SetDelayed gets a reference to the given bool and assigns it to the Delayed field.
func (o *Underlying) SetDelayed(v bool) {
	o.Delayed = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Underlying) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Underlying) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Underlying) SetDescription(v string) {
	o.Description = &v
}

// GetExchangeName returns the ExchangeName field value if set, zero value otherwise.
func (o *Underlying) GetExchangeName() string {
	if o == nil || IsNil(o.ExchangeName) {
		var ret string
		return ret
	}
	return *o.ExchangeName
}

// GetExchangeNameOk returns a tuple with the ExchangeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetExchangeNameOk() (*string, bool) {
	if o == nil || IsNil(o.ExchangeName) {
		return nil, false
	}
	return o.ExchangeName, true
}

// HasExchangeName returns a boolean if a field has been set.
func (o *Underlying) HasExchangeName() bool {
	if o != nil && !IsNil(o.ExchangeName) {
		return true
	}

	return false
}

// SetExchangeName gets a reference to the given string and assigns it to the ExchangeName field.
func (o *Underlying) SetExchangeName(v string) {
	o.ExchangeName = &v
}

// GetFiftyTwoWeekHigh returns the FiftyTwoWeekHigh field value if set, zero value otherwise.
func (o *Underlying) GetFiftyTwoWeekHigh() float64 {
	if o == nil || IsNil(o.FiftyTwoWeekHigh) {
		var ret float64
		return ret
	}
	return *o.FiftyTwoWeekHigh
}

// GetFiftyTwoWeekHighOk returns a tuple with the FiftyTwoWeekHigh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetFiftyTwoWeekHighOk() (*float64, bool) {
	if o == nil || IsNil(o.FiftyTwoWeekHigh) {
		return nil, false
	}
	return o.FiftyTwoWeekHigh, true
}

// HasFiftyTwoWeekHigh returns a boolean if a field has been set.
func (o *Underlying) HasFiftyTwoWeekHigh() bool {
	if o != nil && !IsNil(o.FiftyTwoWeekHigh) {
		return true
	}

	return false
}

// SetFiftyTwoWeekHigh gets a reference to the given float64 and assigns it to the FiftyTwoWeekHigh field.
func (o *Underlying) SetFiftyTwoWeekHigh(v float64) {
	o.FiftyTwoWeekHigh = &v
}

// GetFiftyTwoWeekLow returns the FiftyTwoWeekLow field value if set, zero value otherwise.
func (o *Underlying) GetFiftyTwoWeekLow() float64 {
	if o == nil || IsNil(o.FiftyTwoWeekLow) {
		var ret float64
		return ret
	}
	return *o.FiftyTwoWeekLow
}

// GetFiftyTwoWeekLowOk returns a tuple with the FiftyTwoWeekLow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetFiftyTwoWeekLowOk() (*float64, bool) {
	if o == nil || IsNil(o.FiftyTwoWeekLow) {
		return nil, false
	}
	return o.FiftyTwoWeekLow, true
}

// HasFiftyTwoWeekLow returns a boolean if a field has been set.
func (o *Underlying) HasFiftyTwoWeekLow() bool {
	if o != nil && !IsNil(o.FiftyTwoWeekLow) {
		return true
	}

	return false
}

// SetFiftyTwoWeekLow gets a reference to the given float64 and assigns it to the FiftyTwoWeekLow field.
func (o *Underlying) SetFiftyTwoWeekLow(v float64) {
	o.FiftyTwoWeekLow = &v
}

// GetHighPrice returns the HighPrice field value if set, zero value otherwise.
func (o *Underlying) GetHighPrice() float64 {
	if o == nil || IsNil(o.HighPrice) {
		var ret float64
		return ret
	}
	return *o.HighPrice
}

// GetHighPriceOk returns a tuple with the HighPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetHighPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.HighPrice) {
		return nil, false
	}
	return o.HighPrice, true
}

// HasHighPrice returns a boolean if a field has been set.
func (o *Underlying) HasHighPrice() bool {
	if o != nil && !IsNil(o.HighPrice) {
		return true
	}

	return false
}

// SetHighPrice gets a reference to the given float64 and assigns it to the HighPrice field.
func (o *Underlying) SetHighPrice(v float64) {
	o.HighPrice = &v
}

// GetLast returns the Last field value if set, zero value otherwise.
func (o *Underlying) GetLast() float64 {
	if o == nil || IsNil(o.Last) {
		var ret float64
		return ret
	}
	return *o.Last
}

// GetLastOk returns a tuple with the Last field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetLastOk() (*float64, bool) {
	if o == nil || IsNil(o.Last) {
		return nil, false
	}
	return o.Last, true
}

// HasLast returns a boolean if a field has been set.
func (o *Underlying) HasLast() bool {
	if o != nil && !IsNil(o.Last) {
		return true
	}

	return false
}

// SetLast gets a reference to the given float64 and assigns it to the Last field.
func (o *Underlying) SetLast(v float64) {
	o.Last = &v
}

// GetLowPrice returns the LowPrice field value if set, zero value otherwise.
func (o *Underlying) GetLowPrice() float64 {
	if o == nil || IsNil(o.LowPrice) {
		var ret float64
		return ret
	}
	return *o.LowPrice
}

// GetLowPriceOk returns a tuple with the LowPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetLowPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.LowPrice) {
		return nil, false
	}
	return o.LowPrice, true
}

// HasLowPrice returns a boolean if a field has been set.
func (o *Underlying) HasLowPrice() bool {
	if o != nil && !IsNil(o.LowPrice) {
		return true
	}

	return false
}

// SetLowPrice gets a reference to the given float64 and assigns it to the LowPrice field.
func (o *Underlying) SetLowPrice(v float64) {
	o.LowPrice = &v
}

// GetMark returns the Mark field value if set, zero value otherwise.
func (o *Underlying) GetMark() float64 {
	if o == nil || IsNil(o.Mark) {
		var ret float64
		return ret
	}
	return *o.Mark
}

// GetMarkOk returns a tuple with the Mark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetMarkOk() (*float64, bool) {
	if o == nil || IsNil(o.Mark) {
		return nil, false
	}
	return o.Mark, true
}

// HasMark returns a boolean if a field has been set.
func (o *Underlying) HasMark() bool {
	if o != nil && !IsNil(o.Mark) {
		return true
	}

	return false
}

// SetMark gets a reference to the given float64 and assigns it to the Mark field.
func (o *Underlying) SetMark(v float64) {
	o.Mark = &v
}

// GetMarkChange returns the MarkChange field value if set, zero value otherwise.
func (o *Underlying) GetMarkChange() float64 {
	if o == nil || IsNil(o.MarkChange) {
		var ret float64
		return ret
	}
	return *o.MarkChange
}

// GetMarkChangeOk returns a tuple with the MarkChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetMarkChangeOk() (*float64, bool) {
	if o == nil || IsNil(o.MarkChange) {
		return nil, false
	}
	return o.MarkChange, true
}

// HasMarkChange returns a boolean if a field has been set.
func (o *Underlying) HasMarkChange() bool {
	if o != nil && !IsNil(o.MarkChange) {
		return true
	}

	return false
}

// SetMarkChange gets a reference to the given float64 and assigns it to the MarkChange field.
func (o *Underlying) SetMarkChange(v float64) {
	o.MarkChange = &v
}

// GetMarkPercentChange returns the MarkPercentChange field value if set, zero value otherwise.
func (o *Underlying) GetMarkPercentChange() float64 {
	if o == nil || IsNil(o.MarkPercentChange) {
		var ret float64
		return ret
	}
	return *o.MarkPercentChange
}

// GetMarkPercentChangeOk returns a tuple with the MarkPercentChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetMarkPercentChangeOk() (*float64, bool) {
	if o == nil || IsNil(o.MarkPercentChange) {
		return nil, false
	}
	return o.MarkPercentChange, true
}

// HasMarkPercentChange returns a boolean if a field has been set.
func (o *Underlying) HasMarkPercentChange() bool {
	if o != nil && !IsNil(o.MarkPercentChange) {
		return true
	}

	return false
}

// SetMarkPercentChange gets a reference to the given float64 and assigns it to the MarkPercentChange field.
func (o *Underlying) SetMarkPercentChange(v float64) {
	o.MarkPercentChange = &v
}

// GetOpenPrice returns the OpenPrice field value if set, zero value otherwise.
func (o *Underlying) GetOpenPrice() float64 {
	if o == nil || IsNil(o.OpenPrice) {
		var ret float64
		return ret
	}
	return *o.OpenPrice
}

// GetOpenPriceOk returns a tuple with the OpenPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetOpenPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.OpenPrice) {
		return nil, false
	}
	return o.OpenPrice, true
}

// HasOpenPrice returns a boolean if a field has been set.
func (o *Underlying) HasOpenPrice() bool {
	if o != nil && !IsNil(o.OpenPrice) {
		return true
	}

	return false
}

// SetOpenPrice gets a reference to the given float64 and assigns it to the OpenPrice field.
func (o *Underlying) SetOpenPrice(v float64) {
	o.OpenPrice = &v
}

// GetPercentChange returns the PercentChange field value if set, zero value otherwise.
func (o *Underlying) GetPercentChange() float64 {
	if o == nil || IsNil(o.PercentChange) {
		var ret float64
		return ret
	}
	return *o.PercentChange
}

// GetPercentChangeOk returns a tuple with the PercentChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetPercentChangeOk() (*float64, bool) {
	if o == nil || IsNil(o.PercentChange) {
		return nil, false
	}
	return o.PercentChange, true
}

// HasPercentChange returns a boolean if a field has been set.
func (o *Underlying) HasPercentChange() bool {
	if o != nil && !IsNil(o.PercentChange) {
		return true
	}

	return false
}

// SetPercentChange gets a reference to the given float64 and assigns it to the PercentChange field.
func (o *Underlying) SetPercentChange(v float64) {
	o.PercentChange = &v
}

// GetQuoteTime returns the QuoteTime field value if set, zero value otherwise.
func (o *Underlying) GetQuoteTime() int64 {
	if o == nil || IsNil(o.QuoteTime) {
		var ret int64
		return ret
	}
	return *o.QuoteTime
}

// GetQuoteTimeOk returns a tuple with the QuoteTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetQuoteTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.QuoteTime) {
		return nil, false
	}
	return o.QuoteTime, true
}

// HasQuoteTime returns a boolean if a field has been set.
func (o *Underlying) HasQuoteTime() bool {
	if o != nil && !IsNil(o.QuoteTime) {
		return true
	}

	return false
}

// SetQuoteTime gets a reference to the given int64 and assigns it to the QuoteTime field.
func (o *Underlying) SetQuoteTime(v int64) {
	o.QuoteTime = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *Underlying) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *Underlying) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *Underlying) SetSymbol(v string) {
	o.Symbol = &v
}

// GetTotalVolume returns the TotalVolume field value if set, zero value otherwise.
func (o *Underlying) GetTotalVolume() int64 {
	if o == nil || IsNil(o.TotalVolume) {
		var ret int64
		return ret
	}
	return *o.TotalVolume
}

// GetTotalVolumeOk returns a tuple with the TotalVolume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetTotalVolumeOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalVolume) {
		return nil, false
	}
	return o.TotalVolume, true
}

// HasTotalVolume returns a boolean if a field has been set.
func (o *Underlying) HasTotalVolume() bool {
	if o != nil && !IsNil(o.TotalVolume) {
		return true
	}

	return false
}

// SetTotalVolume gets a reference to the given int64 and assigns it to the TotalVolume field.
func (o *Underlying) SetTotalVolume(v int64) {
	o.TotalVolume = &v
}

// GetTradeTime returns the TradeTime field value if set, zero value otherwise.
func (o *Underlying) GetTradeTime() int64 {
	if o == nil || IsNil(o.TradeTime) {
		var ret int64
		return ret
	}
	return *o.TradeTime
}

// GetTradeTimeOk returns a tuple with the TradeTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Underlying) GetTradeTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.TradeTime) {
		return nil, false
	}
	return o.TradeTime, true
}

// HasTradeTime returns a boolean if a field has been set.
func (o *Underlying) HasTradeTime() bool {
	if o != nil && !IsNil(o.TradeTime) {
		return true
	}

	return false
}

// SetTradeTime gets a reference to the given int64 and assigns it to the TradeTime field.
func (o *Underlying) SetTradeTime(v int64) {
	o.TradeTime = &v
}

func (o Underlying) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Underlying) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ask) {
		toSerialize["ask"] = o.Ask
	}
	if !IsNil(o.AskSize) {
		toSerialize["askSize"] = o.AskSize
	}
	if !IsNil(o.Bid) {
		toSerialize["bid"] = o.Bid
	}
	if !IsNil(o.BidSize) {
		toSerialize["bidSize"] = o.BidSize
	}
	if !IsNil(o.Change) {
		toSerialize["change"] = o.Change
	}
	if !IsNil(o.Close) {
		toSerialize["close"] = o.Close
	}
	if !IsNil(o.Delayed) {
		toSerialize["delayed"] = o.Delayed
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ExchangeName) {
		toSerialize["exchangeName"] = o.ExchangeName
	}
	if !IsNil(o.FiftyTwoWeekHigh) {
		toSerialize["fiftyTwoWeekHigh"] = o.FiftyTwoWeekHigh
	}
	if !IsNil(o.FiftyTwoWeekLow) {
		toSerialize["fiftyTwoWeekLow"] = o.FiftyTwoWeekLow
	}
	if !IsNil(o.HighPrice) {
		toSerialize["highPrice"] = o.HighPrice
	}
	if !IsNil(o.Last) {
		toSerialize["last"] = o.Last
	}
	if !IsNil(o.LowPrice) {
		toSerialize["lowPrice"] = o.LowPrice
	}
	if !IsNil(o.Mark) {
		toSerialize["mark"] = o.Mark
	}
	if !IsNil(o.MarkChange) {
		toSerialize["markChange"] = o.MarkChange
	}
	if !IsNil(o.MarkPercentChange) {
		toSerialize["markPercentChange"] = o.MarkPercentChange
	}
	if !IsNil(o.OpenPrice) {
		toSerialize["openPrice"] = o.OpenPrice
	}
	if !IsNil(o.PercentChange) {
		toSerialize["percentChange"] = o.PercentChange
	}
	if !IsNil(o.QuoteTime) {
		toSerialize["quoteTime"] = o.QuoteTime
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.TotalVolume) {
		toSerialize["totalVolume"] = o.TotalVolume
	}
	if !IsNil(o.TradeTime) {
		toSerialize["tradeTime"] = o.TradeTime
	}
	return toSerialize, nil
}

type NullableUnderlying struct {
	value *Underlying
	isSet bool
}

func (v NullableUnderlying) Get() *Underlying {
	return v.value
}

func (v *NullableUnderlying) Set(val *Underlying) {
	v.value = val
	v.isSet = true
}

func (v NullableUnderlying) IsSet() bool {
	return v.isSet
}

func (v *NullableUnderlying) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnderlying(val *Underlying) *NullableUnderlying {
	return &NullableUnderlying{value: val, isSet: true}
}

func (v NullableUnderlying) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnderlying) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


