/*
Market Data

Trader API - Market data

API version: 1.0.0
Contact: TraderAPI@Schwab.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the QuoteFutureOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteFutureOption{}

// QuoteFutureOption Quote data of Option security
type QuoteFutureOption struct {
	// ask MIC code
	AskMICId *string `json:"askMICId,omitempty"`
	// Current Best Ask Price
	AskPrice *float64 `json:"askPrice,omitempty"`
	// Number of shares for ask
	AskSize *int32 `json:"askSize,omitempty"`
	// bid MIC code
	BidMICId *string `json:"bidMICId,omitempty"`
	// Current Best Bid Price
	BidPrice *float64 `json:"bidPrice,omitempty"`
	// Number of shares for bid
	BidSize *int32 `json:"bidSize,omitempty"`
	// Previous day's closing price
	ClosePrice *float64 `json:"closePrice,omitempty"`
	// Day's high trade price
	HighPrice *float64 `json:"highPrice,omitempty"`
	// Last MIC Code
	LastMICId *string `json:"lastMICId,omitempty"`
	LastPrice *float64 `json:"lastPrice,omitempty"`
	// Number of shares traded with last trade
	LastSize *int32 `json:"lastSize,omitempty"`
	// Day's low trade price
	LowPrice *float64 `json:"lowPrice,omitempty"`
	// Mark price
	Mark *float64 `json:"mark,omitempty"`
	// Mark Price change
	MarkChange *float64 `json:"markChange,omitempty"`
	// Current Last-Prev Close
	NetChange *float64 `json:"netChange,omitempty"`
	// Net Percentage Change
	NetPercentChange *float64 `json:"netPercentChange,omitempty"`
	// Open Interest
	OpenInterest *int32 `json:"openInterest,omitempty"`
	// Price at market open
	OpenPrice *float64 `json:"openPrice,omitempty"`
	// Last quote time in milliseconds since Epoch
	QuoteTime *int64 `json:"quoteTime,omitempty"`
	// Status of security
	SecurityStatus *string `json:"securityStatus,omitempty"`
	// Price at market open
	SettlemetPrice *float64 `json:"settlemetPrice,omitempty"`
	// Tick Price
	Tick *float64 `json:"tick,omitempty"`
	// Tick Amount
	TickAmount *float64 `json:"tickAmount,omitempty"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume *int64 `json:"totalVolume,omitempty"`
	// Last trade time in milliseconds since Epoch
	TradeTime *int64 `json:"tradeTime,omitempty"`
}

// NewQuoteFutureOption instantiates a new QuoteFutureOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteFutureOption() *QuoteFutureOption {
	this := QuoteFutureOption{}
	return &this
}

// NewQuoteFutureOptionWithDefaults instantiates a new QuoteFutureOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteFutureOptionWithDefaults() *QuoteFutureOption {
	this := QuoteFutureOption{}
	return &this
}

// GetAskMICId returns the AskMICId field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetAskMICId() string {
	if o == nil || IsNil(o.AskMICId) {
		var ret string
		return ret
	}
	return *o.AskMICId
}

// GetAskMICIdOk returns a tuple with the AskMICId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetAskMICIdOk() (*string, bool) {
	if o == nil || IsNil(o.AskMICId) {
		return nil, false
	}
	return o.AskMICId, true
}

// HasAskMICId returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasAskMICId() bool {
	if o != nil && !IsNil(o.AskMICId) {
		return true
	}

	return false
}

// SetAskMICId gets a reference to the given string and assigns it to the AskMICId field.
func (o *QuoteFutureOption) SetAskMICId(v string) {
	o.AskMICId = &v
}

// GetAskPrice returns the AskPrice field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetAskPrice() float64 {
	if o == nil || IsNil(o.AskPrice) {
		var ret float64
		return ret
	}
	return *o.AskPrice
}

// GetAskPriceOk returns a tuple with the AskPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetAskPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.AskPrice) {
		return nil, false
	}
	return o.AskPrice, true
}

// HasAskPrice returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasAskPrice() bool {
	if o != nil && !IsNil(o.AskPrice) {
		return true
	}

	return false
}

// SetAskPrice gets a reference to the given float64 and assigns it to the AskPrice field.
func (o *QuoteFutureOption) SetAskPrice(v float64) {
	o.AskPrice = &v
}

// GetAskSize returns the AskSize field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetAskSize() int32 {
	if o == nil || IsNil(o.AskSize) {
		var ret int32
		return ret
	}
	return *o.AskSize
}

// GetAskSizeOk returns a tuple with the AskSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetAskSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.AskSize) {
		return nil, false
	}
	return o.AskSize, true
}

// HasAskSize returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasAskSize() bool {
	if o != nil && !IsNil(o.AskSize) {
		return true
	}

	return false
}

// SetAskSize gets a reference to the given int32 and assigns it to the AskSize field.
func (o *QuoteFutureOption) SetAskSize(v int32) {
	o.AskSize = &v
}

// GetBidMICId returns the BidMICId field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetBidMICId() string {
	if o == nil || IsNil(o.BidMICId) {
		var ret string
		return ret
	}
	return *o.BidMICId
}

// GetBidMICIdOk returns a tuple with the BidMICId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetBidMICIdOk() (*string, bool) {
	if o == nil || IsNil(o.BidMICId) {
		return nil, false
	}
	return o.BidMICId, true
}

// HasBidMICId returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasBidMICId() bool {
	if o != nil && !IsNil(o.BidMICId) {
		return true
	}

	return false
}

// SetBidMICId gets a reference to the given string and assigns it to the BidMICId field.
func (o *QuoteFutureOption) SetBidMICId(v string) {
	o.BidMICId = &v
}

// GetBidPrice returns the BidPrice field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetBidPrice() float64 {
	if o == nil || IsNil(o.BidPrice) {
		var ret float64
		return ret
	}
	return *o.BidPrice
}

// GetBidPriceOk returns a tuple with the BidPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetBidPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.BidPrice) {
		return nil, false
	}
	return o.BidPrice, true
}

// HasBidPrice returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasBidPrice() bool {
	if o != nil && !IsNil(o.BidPrice) {
		return true
	}

	return false
}

// SetBidPrice gets a reference to the given float64 and assigns it to the BidPrice field.
func (o *QuoteFutureOption) SetBidPrice(v float64) {
	o.BidPrice = &v
}

// GetBidSize returns the BidSize field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetBidSize() int32 {
	if o == nil || IsNil(o.BidSize) {
		var ret int32
		return ret
	}
	return *o.BidSize
}

// GetBidSizeOk returns a tuple with the BidSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetBidSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.BidSize) {
		return nil, false
	}
	return o.BidSize, true
}

// HasBidSize returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasBidSize() bool {
	if o != nil && !IsNil(o.BidSize) {
		return true
	}

	return false
}

// SetBidSize gets a reference to the given int32 and assigns it to the BidSize field.
func (o *QuoteFutureOption) SetBidSize(v int32) {
	o.BidSize = &v
}

// GetClosePrice returns the ClosePrice field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetClosePrice() float64 {
	if o == nil || IsNil(o.ClosePrice) {
		var ret float64
		return ret
	}
	return *o.ClosePrice
}

// GetClosePriceOk returns a tuple with the ClosePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetClosePriceOk() (*float64, bool) {
	if o == nil || IsNil(o.ClosePrice) {
		return nil, false
	}
	return o.ClosePrice, true
}

// HasClosePrice returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasClosePrice() bool {
	if o != nil && !IsNil(o.ClosePrice) {
		return true
	}

	return false
}

// SetClosePrice gets a reference to the given float64 and assigns it to the ClosePrice field.
func (o *QuoteFutureOption) SetClosePrice(v float64) {
	o.ClosePrice = &v
}

// GetHighPrice returns the HighPrice field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetHighPrice() float64 {
	if o == nil || IsNil(o.HighPrice) {
		var ret float64
		return ret
	}
	return *o.HighPrice
}

// GetHighPriceOk returns a tuple with the HighPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetHighPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.HighPrice) {
		return nil, false
	}
	return o.HighPrice, true
}

// HasHighPrice returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasHighPrice() bool {
	if o != nil && !IsNil(o.HighPrice) {
		return true
	}

	return false
}

// SetHighPrice gets a reference to the given float64 and assigns it to the HighPrice field.
func (o *QuoteFutureOption) SetHighPrice(v float64) {
	o.HighPrice = &v
}

// GetLastMICId returns the LastMICId field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetLastMICId() string {
	if o == nil || IsNil(o.LastMICId) {
		var ret string
		return ret
	}
	return *o.LastMICId
}

// GetLastMICIdOk returns a tuple with the LastMICId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetLastMICIdOk() (*string, bool) {
	if o == nil || IsNil(o.LastMICId) {
		return nil, false
	}
	return o.LastMICId, true
}

// HasLastMICId returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasLastMICId() bool {
	if o != nil && !IsNil(o.LastMICId) {
		return true
	}

	return false
}

// SetLastMICId gets a reference to the given string and assigns it to the LastMICId field.
func (o *QuoteFutureOption) SetLastMICId(v string) {
	o.LastMICId = &v
}

// GetLastPrice returns the LastPrice field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetLastPrice() float64 {
	if o == nil || IsNil(o.LastPrice) {
		var ret float64
		return ret
	}
	return *o.LastPrice
}

// GetLastPriceOk returns a tuple with the LastPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetLastPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.LastPrice) {
		return nil, false
	}
	return o.LastPrice, true
}

// HasLastPrice returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasLastPrice() bool {
	if o != nil && !IsNil(o.LastPrice) {
		return true
	}

	return false
}

// SetLastPrice gets a reference to the given float64 and assigns it to the LastPrice field.
func (o *QuoteFutureOption) SetLastPrice(v float64) {
	o.LastPrice = &v
}

// GetLastSize returns the LastSize field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetLastSize() int32 {
	if o == nil || IsNil(o.LastSize) {
		var ret int32
		return ret
	}
	return *o.LastSize
}

// GetLastSizeOk returns a tuple with the LastSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetLastSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.LastSize) {
		return nil, false
	}
	return o.LastSize, true
}

// HasLastSize returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasLastSize() bool {
	if o != nil && !IsNil(o.LastSize) {
		return true
	}

	return false
}

// SetLastSize gets a reference to the given int32 and assigns it to the LastSize field.
func (o *QuoteFutureOption) SetLastSize(v int32) {
	o.LastSize = &v
}

// GetLowPrice returns the LowPrice field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetLowPrice() float64 {
	if o == nil || IsNil(o.LowPrice) {
		var ret float64
		return ret
	}
	return *o.LowPrice
}

// GetLowPriceOk returns a tuple with the LowPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetLowPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.LowPrice) {
		return nil, false
	}
	return o.LowPrice, true
}

// HasLowPrice returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasLowPrice() bool {
	if o != nil && !IsNil(o.LowPrice) {
		return true
	}

	return false
}

// SetLowPrice gets a reference to the given float64 and assigns it to the LowPrice field.
func (o *QuoteFutureOption) SetLowPrice(v float64) {
	o.LowPrice = &v
}

// GetMark returns the Mark field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetMark() float64 {
	if o == nil || IsNil(o.Mark) {
		var ret float64
		return ret
	}
	return *o.Mark
}

// GetMarkOk returns a tuple with the Mark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetMarkOk() (*float64, bool) {
	if o == nil || IsNil(o.Mark) {
		return nil, false
	}
	return o.Mark, true
}

// HasMark returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasMark() bool {
	if o != nil && !IsNil(o.Mark) {
		return true
	}

	return false
}

// SetMark gets a reference to the given float64 and assigns it to the Mark field.
func (o *QuoteFutureOption) SetMark(v float64) {
	o.Mark = &v
}

// GetMarkChange returns the MarkChange field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetMarkChange() float64 {
	if o == nil || IsNil(o.MarkChange) {
		var ret float64
		return ret
	}
	return *o.MarkChange
}

// GetMarkChangeOk returns a tuple with the MarkChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetMarkChangeOk() (*float64, bool) {
	if o == nil || IsNil(o.MarkChange) {
		return nil, false
	}
	return o.MarkChange, true
}

// HasMarkChange returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasMarkChange() bool {
	if o != nil && !IsNil(o.MarkChange) {
		return true
	}

	return false
}

// SetMarkChange gets a reference to the given float64 and assigns it to the MarkChange field.
func (o *QuoteFutureOption) SetMarkChange(v float64) {
	o.MarkChange = &v
}

// GetNetChange returns the NetChange field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetNetChange() float64 {
	if o == nil || IsNil(o.NetChange) {
		var ret float64
		return ret
	}
	return *o.NetChange
}

// GetNetChangeOk returns a tuple with the NetChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetNetChangeOk() (*float64, bool) {
	if o == nil || IsNil(o.NetChange) {
		return nil, false
	}
	return o.NetChange, true
}

// HasNetChange returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasNetChange() bool {
	if o != nil && !IsNil(o.NetChange) {
		return true
	}

	return false
}

// SetNetChange gets a reference to the given float64 and assigns it to the NetChange field.
func (o *QuoteFutureOption) SetNetChange(v float64) {
	o.NetChange = &v
}

// GetNetPercentChange returns the NetPercentChange field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetNetPercentChange() float64 {
	if o == nil || IsNil(o.NetPercentChange) {
		var ret float64
		return ret
	}
	return *o.NetPercentChange
}

// GetNetPercentChangeOk returns a tuple with the NetPercentChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetNetPercentChangeOk() (*float64, bool) {
	if o == nil || IsNil(o.NetPercentChange) {
		return nil, false
	}
	return o.NetPercentChange, true
}

// HasNetPercentChange returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasNetPercentChange() bool {
	if o != nil && !IsNil(o.NetPercentChange) {
		return true
	}

	return false
}

// SetNetPercentChange gets a reference to the given float64 and assigns it to the NetPercentChange field.
func (o *QuoteFutureOption) SetNetPercentChange(v float64) {
	o.NetPercentChange = &v
}

// GetOpenInterest returns the OpenInterest field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetOpenInterest() int32 {
	if o == nil || IsNil(o.OpenInterest) {
		var ret int32
		return ret
	}
	return *o.OpenInterest
}

// GetOpenInterestOk returns a tuple with the OpenInterest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetOpenInterestOk() (*int32, bool) {
	if o == nil || IsNil(o.OpenInterest) {
		return nil, false
	}
	return o.OpenInterest, true
}

// HasOpenInterest returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasOpenInterest() bool {
	if o != nil && !IsNil(o.OpenInterest) {
		return true
	}

	return false
}

// SetOpenInterest gets a reference to the given int32 and assigns it to the OpenInterest field.
func (o *QuoteFutureOption) SetOpenInterest(v int32) {
	o.OpenInterest = &v
}

// GetOpenPrice returns the OpenPrice field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetOpenPrice() float64 {
	if o == nil || IsNil(o.OpenPrice) {
		var ret float64
		return ret
	}
	return *o.OpenPrice
}

// GetOpenPriceOk returns a tuple with the OpenPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetOpenPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.OpenPrice) {
		return nil, false
	}
	return o.OpenPrice, true
}

// HasOpenPrice returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasOpenPrice() bool {
	if o != nil && !IsNil(o.OpenPrice) {
		return true
	}

	return false
}

// SetOpenPrice gets a reference to the given float64 and assigns it to the OpenPrice field.
func (o *QuoteFutureOption) SetOpenPrice(v float64) {
	o.OpenPrice = &v
}

// GetQuoteTime returns the QuoteTime field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetQuoteTime() int64 {
	if o == nil || IsNil(o.QuoteTime) {
		var ret int64
		return ret
	}
	return *o.QuoteTime
}

// GetQuoteTimeOk returns a tuple with the QuoteTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetQuoteTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.QuoteTime) {
		return nil, false
	}
	return o.QuoteTime, true
}

// HasQuoteTime returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasQuoteTime() bool {
	if o != nil && !IsNil(o.QuoteTime) {
		return true
	}

	return false
}

// SetQuoteTime gets a reference to the given int64 and assigns it to the QuoteTime field.
func (o *QuoteFutureOption) SetQuoteTime(v int64) {
	o.QuoteTime = &v
}

// GetSecurityStatus returns the SecurityStatus field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetSecurityStatus() string {
	if o == nil || IsNil(o.SecurityStatus) {
		var ret string
		return ret
	}
	return *o.SecurityStatus
}

// GetSecurityStatusOk returns a tuple with the SecurityStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetSecurityStatusOk() (*string, bool) {
	if o == nil || IsNil(o.SecurityStatus) {
		return nil, false
	}
	return o.SecurityStatus, true
}

// HasSecurityStatus returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasSecurityStatus() bool {
	if o != nil && !IsNil(o.SecurityStatus) {
		return true
	}

	return false
}

// SetSecurityStatus gets a reference to the given string and assigns it to the SecurityStatus field.
func (o *QuoteFutureOption) SetSecurityStatus(v string) {
	o.SecurityStatus = &v
}

// GetSettlemetPrice returns the SettlemetPrice field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetSettlemetPrice() float64 {
	if o == nil || IsNil(o.SettlemetPrice) {
		var ret float64
		return ret
	}
	return *o.SettlemetPrice
}

// GetSettlemetPriceOk returns a tuple with the SettlemetPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetSettlemetPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.SettlemetPrice) {
		return nil, false
	}
	return o.SettlemetPrice, true
}

// HasSettlemetPrice returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasSettlemetPrice() bool {
	if o != nil && !IsNil(o.SettlemetPrice) {
		return true
	}

	return false
}

// SetSettlemetPrice gets a reference to the given float64 and assigns it to the SettlemetPrice field.
func (o *QuoteFutureOption) SetSettlemetPrice(v float64) {
	o.SettlemetPrice = &v
}

// GetTick returns the Tick field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetTick() float64 {
	if o == nil || IsNil(o.Tick) {
		var ret float64
		return ret
	}
	return *o.Tick
}

// GetTickOk returns a tuple with the Tick field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetTickOk() (*float64, bool) {
	if o == nil || IsNil(o.Tick) {
		return nil, false
	}
	return o.Tick, true
}

// HasTick returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasTick() bool {
	if o != nil && !IsNil(o.Tick) {
		return true
	}

	return false
}

// SetTick gets a reference to the given float64 and assigns it to the Tick field.
func (o *QuoteFutureOption) SetTick(v float64) {
	o.Tick = &v
}

// GetTickAmount returns the TickAmount field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetTickAmount() float64 {
	if o == nil || IsNil(o.TickAmount) {
		var ret float64
		return ret
	}
	return *o.TickAmount
}

// GetTickAmountOk returns a tuple with the TickAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetTickAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.TickAmount) {
		return nil, false
	}
	return o.TickAmount, true
}

// HasTickAmount returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasTickAmount() bool {
	if o != nil && !IsNil(o.TickAmount) {
		return true
	}

	return false
}

// SetTickAmount gets a reference to the given float64 and assigns it to the TickAmount field.
func (o *QuoteFutureOption) SetTickAmount(v float64) {
	o.TickAmount = &v
}

// GetTotalVolume returns the TotalVolume field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetTotalVolume() int64 {
	if o == nil || IsNil(o.TotalVolume) {
		var ret int64
		return ret
	}
	return *o.TotalVolume
}

// GetTotalVolumeOk returns a tuple with the TotalVolume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetTotalVolumeOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalVolume) {
		return nil, false
	}
	return o.TotalVolume, true
}

// HasTotalVolume returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasTotalVolume() bool {
	if o != nil && !IsNil(o.TotalVolume) {
		return true
	}

	return false
}

// SetTotalVolume gets a reference to the given int64 and assigns it to the TotalVolume field.
func (o *QuoteFutureOption) SetTotalVolume(v int64) {
	o.TotalVolume = &v
}

// GetTradeTime returns the TradeTime field value if set, zero value otherwise.
func (o *QuoteFutureOption) GetTradeTime() int64 {
	if o == nil || IsNil(o.TradeTime) {
		var ret int64
		return ret
	}
	return *o.TradeTime
}

// GetTradeTimeOk returns a tuple with the TradeTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteFutureOption) GetTradeTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.TradeTime) {
		return nil, false
	}
	return o.TradeTime, true
}

// HasTradeTime returns a boolean if a field has been set.
func (o *QuoteFutureOption) HasTradeTime() bool {
	if o != nil && !IsNil(o.TradeTime) {
		return true
	}

	return false
}

// SetTradeTime gets a reference to the given int64 and assigns it to the TradeTime field.
func (o *QuoteFutureOption) SetTradeTime(v int64) {
	o.TradeTime = &v
}

func (o QuoteFutureOption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteFutureOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AskMICId) {
		toSerialize["askMICId"] = o.AskMICId
	}
	if !IsNil(o.AskPrice) {
		toSerialize["askPrice"] = o.AskPrice
	}
	if !IsNil(o.AskSize) {
		toSerialize["askSize"] = o.AskSize
	}
	if !IsNil(o.BidMICId) {
		toSerialize["bidMICId"] = o.BidMICId
	}
	if !IsNil(o.BidPrice) {
		toSerialize["bidPrice"] = o.BidPrice
	}
	if !IsNil(o.BidSize) {
		toSerialize["bidSize"] = o.BidSize
	}
	if !IsNil(o.ClosePrice) {
		toSerialize["closePrice"] = o.ClosePrice
	}
	if !IsNil(o.HighPrice) {
		toSerialize["highPrice"] = o.HighPrice
	}
	if !IsNil(o.LastMICId) {
		toSerialize["lastMICId"] = o.LastMICId
	}
	if !IsNil(o.LastPrice) {
		toSerialize["lastPrice"] = o.LastPrice
	}
	if !IsNil(o.LastSize) {
		toSerialize["lastSize"] = o.LastSize
	}
	if !IsNil(o.LowPrice) {
		toSerialize["lowPrice"] = o.LowPrice
	}
	if !IsNil(o.Mark) {
		toSerialize["mark"] = o.Mark
	}
	if !IsNil(o.MarkChange) {
		toSerialize["markChange"] = o.MarkChange
	}
	if !IsNil(o.NetChange) {
		toSerialize["netChange"] = o.NetChange
	}
	if !IsNil(o.NetPercentChange) {
		toSerialize["netPercentChange"] = o.NetPercentChange
	}
	if !IsNil(o.OpenInterest) {
		toSerialize["openInterest"] = o.OpenInterest
	}
	if !IsNil(o.OpenPrice) {
		toSerialize["openPrice"] = o.OpenPrice
	}
	if !IsNil(o.QuoteTime) {
		toSerialize["quoteTime"] = o.QuoteTime
	}
	if !IsNil(o.SecurityStatus) {
		toSerialize["securityStatus"] = o.SecurityStatus
	}
	if !IsNil(o.SettlemetPrice) {
		toSerialize["settlemetPrice"] = o.SettlemetPrice
	}
	if !IsNil(o.Tick) {
		toSerialize["tick"] = o.Tick
	}
	if !IsNil(o.TickAmount) {
		toSerialize["tickAmount"] = o.TickAmount
	}
	if !IsNil(o.TotalVolume) {
		toSerialize["totalVolume"] = o.TotalVolume
	}
	if !IsNil(o.TradeTime) {
		toSerialize["tradeTime"] = o.TradeTime
	}
	return toSerialize, nil
}

type NullableQuoteFutureOption struct {
	value *QuoteFutureOption
	isSet bool
}

func (v NullableQuoteFutureOption) Get() *QuoteFutureOption {
	return v.value
}

func (v *NullableQuoteFutureOption) Set(val *QuoteFutureOption) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteFutureOption) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteFutureOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteFutureOption(val *QuoteFutureOption) *NullableQuoteFutureOption {
	return &NullableQuoteFutureOption{value: val, isSet: true}
}

func (v NullableQuoteFutureOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteFutureOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


