/*
Market Data

Trader API - Market data

API version: 1.0.0
Contact: TraderAPI@Schwab.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the QuoteMutualFund type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteMutualFund{}

// QuoteMutualFund Quote data of Mutual Fund security
type QuoteMutualFund struct {
	// Higest price traded in the past 12 months, or 52 weeks
	Var52WeekHigh *float64 `json:"52WeekHigh,omitempty"`
	// Lowest price traded in the past 12 months, or 52 weeks
	Var52WeekLow *float64 `json:"52WeekLow,omitempty"`
	// Previous day's closing price
	ClosePrice *float64 `json:"closePrice,omitempty"`
	// Net Asset Value
	NAV *float64 `json:"nAV,omitempty"`
	// Current Last-Prev Close
	NetChange *float64 `json:"netChange,omitempty"`
	// Net Percentage Change
	NetPercentChange *float64 `json:"netPercentChange,omitempty"`
	// Status of security
	SecurityStatus *string `json:"securityStatus,omitempty"`
	// Aggregated shares traded throughout the day, including pre/post market hours.
	TotalVolume *int64 `json:"totalVolume,omitempty"`
	// Last trade time in milliseconds since Epoch
	TradeTime *int64 `json:"tradeTime,omitempty"`
}

// NewQuoteMutualFund instantiates a new QuoteMutualFund object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteMutualFund() *QuoteMutualFund {
	this := QuoteMutualFund{}
	return &this
}

// NewQuoteMutualFundWithDefaults instantiates a new QuoteMutualFund object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteMutualFundWithDefaults() *QuoteMutualFund {
	this := QuoteMutualFund{}
	return &this
}

// GetVar52WeekHigh returns the Var52WeekHigh field value if set, zero value otherwise.
func (o *QuoteMutualFund) GetVar52WeekHigh() float64 {
	if o == nil || IsNil(o.Var52WeekHigh) {
		var ret float64
		return ret
	}
	return *o.Var52WeekHigh
}

// GetVar52WeekHighOk returns a tuple with the Var52WeekHigh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteMutualFund) GetVar52WeekHighOk() (*float64, bool) {
	if o == nil || IsNil(o.Var52WeekHigh) {
		return nil, false
	}
	return o.Var52WeekHigh, true
}

// HasVar52WeekHigh returns a boolean if a field has been set.
func (o *QuoteMutualFund) HasVar52WeekHigh() bool {
	if o != nil && !IsNil(o.Var52WeekHigh) {
		return true
	}

	return false
}

// SetVar52WeekHigh gets a reference to the given float64 and assigns it to the Var52WeekHigh field.
func (o *QuoteMutualFund) SetVar52WeekHigh(v float64) {
	o.Var52WeekHigh = &v
}

// GetVar52WeekLow returns the Var52WeekLow field value if set, zero value otherwise.
func (o *QuoteMutualFund) GetVar52WeekLow() float64 {
	if o == nil || IsNil(o.Var52WeekLow) {
		var ret float64
		return ret
	}
	return *o.Var52WeekLow
}

// GetVar52WeekLowOk returns a tuple with the Var52WeekLow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteMutualFund) GetVar52WeekLowOk() (*float64, bool) {
	if o == nil || IsNil(o.Var52WeekLow) {
		return nil, false
	}
	return o.Var52WeekLow, true
}

// HasVar52WeekLow returns a boolean if a field has been set.
func (o *QuoteMutualFund) HasVar52WeekLow() bool {
	if o != nil && !IsNil(o.Var52WeekLow) {
		return true
	}

	return false
}

// SetVar52WeekLow gets a reference to the given float64 and assigns it to the Var52WeekLow field.
func (o *QuoteMutualFund) SetVar52WeekLow(v float64) {
	o.Var52WeekLow = &v
}

// GetClosePrice returns the ClosePrice field value if set, zero value otherwise.
func (o *QuoteMutualFund) GetClosePrice() float64 {
	if o == nil || IsNil(o.ClosePrice) {
		var ret float64
		return ret
	}
	return *o.ClosePrice
}

// GetClosePriceOk returns a tuple with the ClosePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteMutualFund) GetClosePriceOk() (*float64, bool) {
	if o == nil || IsNil(o.ClosePrice) {
		return nil, false
	}
	return o.ClosePrice, true
}

// HasClosePrice returns a boolean if a field has been set.
func (o *QuoteMutualFund) HasClosePrice() bool {
	if o != nil && !IsNil(o.ClosePrice) {
		return true
	}

	return false
}

// SetClosePrice gets a reference to the given float64 and assigns it to the ClosePrice field.
func (o *QuoteMutualFund) SetClosePrice(v float64) {
	o.ClosePrice = &v
}

// GetNAV returns the NAV field value if set, zero value otherwise.
func (o *QuoteMutualFund) GetNAV() float64 {
	if o == nil || IsNil(o.NAV) {
		var ret float64
		return ret
	}
	return *o.NAV
}

// GetNAVOk returns a tuple with the NAV field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteMutualFund) GetNAVOk() (*float64, bool) {
	if o == nil || IsNil(o.NAV) {
		return nil, false
	}
	return o.NAV, true
}

// HasNAV returns a boolean if a field has been set.
func (o *QuoteMutualFund) HasNAV() bool {
	if o != nil && !IsNil(o.NAV) {
		return true
	}

	return false
}

// SetNAV gets a reference to the given float64 and assigns it to the NAV field.
func (o *QuoteMutualFund) SetNAV(v float64) {
	o.NAV = &v
}

// GetNetChange returns the NetChange field value if set, zero value otherwise.
func (o *QuoteMutualFund) GetNetChange() float64 {
	if o == nil || IsNil(o.NetChange) {
		var ret float64
		return ret
	}
	return *o.NetChange
}

// GetNetChangeOk returns a tuple with the NetChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteMutualFund) GetNetChangeOk() (*float64, bool) {
	if o == nil || IsNil(o.NetChange) {
		return nil, false
	}
	return o.NetChange, true
}

// HasNetChange returns a boolean if a field has been set.
func (o *QuoteMutualFund) HasNetChange() bool {
	if o != nil && !IsNil(o.NetChange) {
		return true
	}

	return false
}

// SetNetChange gets a reference to the given float64 and assigns it to the NetChange field.
func (o *QuoteMutualFund) SetNetChange(v float64) {
	o.NetChange = &v
}

// GetNetPercentChange returns the NetPercentChange field value if set, zero value otherwise.
func (o *QuoteMutualFund) GetNetPercentChange() float64 {
	if o == nil || IsNil(o.NetPercentChange) {
		var ret float64
		return ret
	}
	return *o.NetPercentChange
}

// GetNetPercentChangeOk returns a tuple with the NetPercentChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteMutualFund) GetNetPercentChangeOk() (*float64, bool) {
	if o == nil || IsNil(o.NetPercentChange) {
		return nil, false
	}
	return o.NetPercentChange, true
}

// HasNetPercentChange returns a boolean if a field has been set.
func (o *QuoteMutualFund) HasNetPercentChange() bool {
	if o != nil && !IsNil(o.NetPercentChange) {
		return true
	}

	return false
}

// SetNetPercentChange gets a reference to the given float64 and assigns it to the NetPercentChange field.
func (o *QuoteMutualFund) SetNetPercentChange(v float64) {
	o.NetPercentChange = &v
}

// GetSecurityStatus returns the SecurityStatus field value if set, zero value otherwise.
func (o *QuoteMutualFund) GetSecurityStatus() string {
	if o == nil || IsNil(o.SecurityStatus) {
		var ret string
		return ret
	}
	return *o.SecurityStatus
}

// GetSecurityStatusOk returns a tuple with the SecurityStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteMutualFund) GetSecurityStatusOk() (*string, bool) {
	if o == nil || IsNil(o.SecurityStatus) {
		return nil, false
	}
	return o.SecurityStatus, true
}

// HasSecurityStatus returns a boolean if a field has been set.
func (o *QuoteMutualFund) HasSecurityStatus() bool {
	if o != nil && !IsNil(o.SecurityStatus) {
		return true
	}

	return false
}

// SetSecurityStatus gets a reference to the given string and assigns it to the SecurityStatus field.
func (o *QuoteMutualFund) SetSecurityStatus(v string) {
	o.SecurityStatus = &v
}

// GetTotalVolume returns the TotalVolume field value if set, zero value otherwise.
func (o *QuoteMutualFund) GetTotalVolume() int64 {
	if o == nil || IsNil(o.TotalVolume) {
		var ret int64
		return ret
	}
	return *o.TotalVolume
}

// GetTotalVolumeOk returns a tuple with the TotalVolume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteMutualFund) GetTotalVolumeOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalVolume) {
		return nil, false
	}
	return o.TotalVolume, true
}

// HasTotalVolume returns a boolean if a field has been set.
func (o *QuoteMutualFund) HasTotalVolume() bool {
	if o != nil && !IsNil(o.TotalVolume) {
		return true
	}

	return false
}

// SetTotalVolume gets a reference to the given int64 and assigns it to the TotalVolume field.
func (o *QuoteMutualFund) SetTotalVolume(v int64) {
	o.TotalVolume = &v
}

// GetTradeTime returns the TradeTime field value if set, zero value otherwise.
func (o *QuoteMutualFund) GetTradeTime() int64 {
	if o == nil || IsNil(o.TradeTime) {
		var ret int64
		return ret
	}
	return *o.TradeTime
}

// GetTradeTimeOk returns a tuple with the TradeTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteMutualFund) GetTradeTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.TradeTime) {
		return nil, false
	}
	return o.TradeTime, true
}

// HasTradeTime returns a boolean if a field has been set.
func (o *QuoteMutualFund) HasTradeTime() bool {
	if o != nil && !IsNil(o.TradeTime) {
		return true
	}

	return false
}

// SetTradeTime gets a reference to the given int64 and assigns it to the TradeTime field.
func (o *QuoteMutualFund) SetTradeTime(v int64) {
	o.TradeTime = &v
}

func (o QuoteMutualFund) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteMutualFund) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Var52WeekHigh) {
		toSerialize["52WeekHigh"] = o.Var52WeekHigh
	}
	if !IsNil(o.Var52WeekLow) {
		toSerialize["52WeekLow"] = o.Var52WeekLow
	}
	if !IsNil(o.ClosePrice) {
		toSerialize["closePrice"] = o.ClosePrice
	}
	if !IsNil(o.NAV) {
		toSerialize["nAV"] = o.NAV
	}
	if !IsNil(o.NetChange) {
		toSerialize["netChange"] = o.NetChange
	}
	if !IsNil(o.NetPercentChange) {
		toSerialize["netPercentChange"] = o.NetPercentChange
	}
	if !IsNil(o.SecurityStatus) {
		toSerialize["securityStatus"] = o.SecurityStatus
	}
	if !IsNil(o.TotalVolume) {
		toSerialize["totalVolume"] = o.TotalVolume
	}
	if !IsNil(o.TradeTime) {
		toSerialize["tradeTime"] = o.TradeTime
	}
	return toSerialize, nil
}

type NullableQuoteMutualFund struct {
	value *QuoteMutualFund
	isSet bool
}

func (v NullableQuoteMutualFund) Get() *QuoteMutualFund {
	return v.value
}

func (v *NullableQuoteMutualFund) Set(val *QuoteMutualFund) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteMutualFund) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteMutualFund) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteMutualFund(val *QuoteMutualFund) *NullableQuoteMutualFund {
	return &NullableQuoteMutualFund{value: val, isSet: true}
}

func (v NullableQuoteMutualFund) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteMutualFund) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


